require("config")
vim.cmd('colorscheme rose-pine')
vim.cmd('colorscheme dracula')
vim.cmd('colorscheme gotham256')
vim.cmd('colorscheme nightfly')
vim.cmd('colorscheme gruvbox')
vim.cmd('colorscheme tokyonight')
vim.cmd('colorscheme material-darker')
vim.cmd('colorscheme synthwave84')
vim.cmd('colorscheme tokyonight-night')
